export const PERMISSIONS = {
  // User management
  USER_MANAGE: "USER_MANAGE",

  // Masters
  MASTER_MANAGE: "MASTER_MANAGE",

  // Schemes
  SCHEME_CREATE: "SCHEME_CREATE",
  SCHEME_EDIT: "SCHEME_EDIT",
  SCHEME_VIEW: "SCHEME_VIEW",
  SCHEME_ASSIGN: "SCHEME_ASSIGN",

  // Scheme Answers
  SCHEME_ANSWER: "SCHEME_ANSWER",

  // Excel
  EXCEL_UPLOAD: "EXCEL_UPLOAD",
  EXCEL_EXPORT: "EXCEL_EXPORT"
};
